### ISSUE TITLE
No configure script

### ISSUE THREAD

**Issue by smoretti** [ddarriba/ForeSeqs#1]
Hi
the repository does not contain any configure script as mentioned in the INSTALL file.
And autoconf/automake return errors for me.

What is the right way to compile the ForeSeqs?

Thanks

**Comment by ddarriba** [comment]
Could you try running 'autoreconf -i' on the clean repository? If it doesn't work let me know what error you get.
Also, make sure that you have installed the latest libpll before (libpll.org).
El 1/7/2016 1:43 p. m., smoretti notifications@github.com escribió:Hi
the repository does not contain any configure script as mentioned in the INSTALL file.
And autoconf/automake return errors for me.

What is the right way to compile the ForeSeqs?

Thanks

**Comment by smoretti** [comment]
Thanks, configure script appears now.

Then compilation works without warnings but the binary does not work.
I had to force a static build to make it work. I will investigate more newt week.

Thanks

**Comment by smoretti** [comment]
I had issues in my terminal with LIBRARY. So need to force compilation as static binary to make it work.

Thanks
