### ISSUE TITLE
Evaluate Likelihood error

### ISSUE THREAD

**Issue by carloliveros** [ddarriba/ForeSeqs#4]
Hi Diego,

I am encountering the following error in my ForeSeqs run:

`evaluateGenericSpecial.c:1985: pllEvaluateLikelihood: Assertion "(((tr->likelihood - likelihood)<0) ? (-(tr->likelihood - likelihood)) : (tr->likelihood - likelihood)) < 0.00001" failed`

I encounter it after invoking ForeSeqs with:  

`foreseqs -i alignment.phylip -t newick.tre  -q alignment.part -b s -p s | tee foreseqs.samp1.out`

The last screen output before the error is: 

`Tree with stolen branches for partition 593:`

Any idea what could be causing this?

This alignment represents 1/4 of my dataset.  I have run ForeSeqs with the same invocation on the three other subsets with no problem, which to me suggests that there is something wrong with this dataset or a particular partition.

Cheers
Carl

**Comment by carloliveros** [comment]
Also,  If a specific partition is the problem, how do I identify which one it is in my alignment?  Let's say the problem is with partition 595, is it the 596th partition (because ForeSeqs starts with partition 0) as defined in the partition file?  Or is it the 596th partition in the alignment, counting partitions from left to right?

**Comment by ddarriba** [comment]
Hi Carl,

The error should be in 596th partition in the order defined in the partitions file. Do you observe any weird output such as weird Gamma rate categories assignment or estimated branch lengths? Could you please send me the input files? Send me a personal mail for that if you do not want to publish your data.

**Comment by carloliveros** [comment]
Just to give you an update, I removed the loci on which the program was giving me the error and it finally gave me an alignment.  I had to remove 2 loci from the total >1000 loci so I had to rerun the program twice to find the problematic loci.  Still don't know what was causing the error but for my purposes, I'm happy with discarding 2 loci.  Thanks, Diego!
